### ISSUE TITLE
Add discription of Town, Mayor, Street and House Entity

### ISSUE THREAD

**Issue by michael-sevcik** [michael-sevcik/NPRG036-Data-Formats#1]
To complete the [1st hw](https://jakub.xn--klmek-0sa.com/nprg036-hw1), we need to add a discription of Town, Mayor, Street and House entity and the corresponding relations. See [domain.txt](https://github.com/michael-sevcik/NPRG036-Data-Formats/blob/main/domain.txt).

**Comment by patinoboh** [comment]
Did [my part](https://github.com/michael-sevcik/NPRG036-Data-Formats/commit/27f7436bd59d45730255898774a6bc6eefbf3f9d)

**Comment by patinoboh** [comment]
Leader @ori-no should make the final revision so we can close this milestone and send it.

**Comment by ori-no** [comment]
About to review, be ready to correct your mistakes @patinoboh :)))

**Comment by ori-no** [comment]
Reviewed, IMO domain.txt is good.
