### ISSUE TITLE
Start new milestone for the second homework

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#13]
Esketit so we can start spamming this damn site again

**Comment by michael-sevcik** [comment]
I sugest that each of us will convert the entities for which we had written the description to the form described in the [HW 2 assignment 1 and 2 paragraph](https://jakub.xn--klmek-0sa.com/nprg036-hw2#:~:text=Fix%20the%20conceptual,domain%20and%20range.).

**Comment by patinoboh** [comment]
Someone (@ori-no ) could start by making a template for us.
