### ISSUE TITLE
Feedback from Jakub Klímek - minor issue

### ISSUE THREAD

**Issue by ori-no** [michael-sevcik/NPRG036-Data-Formats#14]
Dobrý den,

Je to v pořádku, mám jen jednu poznámku a jednu minor issue:
Váš model zachycuje vlastně snapshot v čase - město má vždy jednoho mayora - tedy nebudu moci vědět, kdo všechno byl daného města mayorem. To může být v pořádku, pokud je to záměr.
Colour - pokud by to měl být výčet (červená, zelená) tak jak to máte v příkladu, - pak by to byla separátní třída, s názvem, připojená asociací, protože to jsou separátní objekty reálného světa. Jako atribut bych to použil, kdyby to byl třeba kód v RGB, nikoliv pojmenovaná entita - tedy upravte jedním či druhým způsobem.
S pozdravem,
Jakub Klímek

**Comment by patinoboh** [comment]
I'll change the color somehow. The first point is right, however I suggest we proclaim that as our intention. I do not see any problem with that.

**Comment by michael-sevcik** [comment]
Is there any progress?

**Comment by patinoboh** [comment]
I changed the color [here](https://github.com/michael-sevcik/NPRG036-Data-Formats/commit/2903b0cab0a2729ad61b1396053da302e1d22ed8). If @ori-no does not want to change the first part we might close this issue.

**Comment by ori-no** [comment]
We can agree that it is a snapshot of town in certain time so exactly 1 mayor is fine in that context.
I will upload the updated version to SIS.
