### ISSUE TITLE
Template for HW2

### ISSUE THREAD

**Issue by michael-sevcik** [michael-sevcik/NPRG036-Data-Formats#17]
As was proposed in #13, we should create a template for the HW2 description of entities and also agree upon the division of work in the team.

**Comment by michael-sevcik** [comment]
## For my part 

### Mapping of used properties to existing terms

#### Person

| Original term | New term |
| ----------- | -------------- |
| name | foaf:firstName      |
| middlename | ex:middleNames - list |
| surname | foaf:surname |

#### Occupant

| Original term | New term |
| ----------- | -------------- |
| date_from | ex:dateFrom      |
| unpaid_fees | ex:unpaidFees |
| lives_in | ex:livesIn |

### New terms for the custom dictionary

```RDF
# Definition of Person  and its propererties
ex:Person a foaf:Person ;
	rdfs:label "Osoba"@cs;
	rdfs:comment "Osoba se jménem"@cs .


TODO: ex:middleNames - list

ex:middleNames a rdf:Property ;
	rdfs:label "Middle Names"@en ;
	rdfs:comment "Represents the middle names of an individual as a list." .
	rdfs:domain ex:Person;
	rdfs:range ex:MiddleNameList .

ex:MiddleNameList a rdf:List ; // abstraction
	rdf:first "Anne" ;
	rdf:rest (
	[ rdf:first "Elizabeth" ;
		rdf:rest rdf:nil ]
	) .

# Definition of Occupant and its propererties
ex:Occupant rdfs:subClassOf ex:Person;
	rdfs:label "Obyvatel domu"@cs;
	rdfs:comment "Osoba obývající dům."@cs .

ex:dateFrom a rdf:Property ;
	rdfs:label "Datum počátku pobytu"@en ;
	rdfs:comment "Datum, kdy osoba započala svůj trvalý pobyt." .
	rdfs:domain ex:Occupant ;
	rdfs:range xsd:date.

ex:unpaidFees a rdf:Property ;
	rdfs:label "Nezaplacené poplatky"@cs;
	rdfs:comment "Indikuje, zda daná osoba má nějaké nezaplacené poplatky." .
	rdfs:domain ex:Occupant ;
	rdfs:range xsd:boolean.

ex:livesIn a rdf:Property ;
	rdfs:label "Obývá"@cs ;
	rdfs:comment "Kde daná osoba má trvalý pobyt." .
	rdfs:domain ex:Occupant ;
	rdfs:range ex:House .

```

**Comment by michael-sevcik** [comment]
Definition of ex:middleNames will be finished after consulting it with the professor.

**Comment by michael-sevcik** [comment]
@ori-no, @patinoboh, @rastoboh please use this as a template for the rest of entities.

**Comment by patinoboh** [comment]
Good job @michael-sevcik, looks great, thank you for the efford. Why not put the whole thing in a file already?

**Comment by patinoboh** [comment]
So you suggest making the whole (almost) dictionary by our own? I am not against that since finding right terms online is painful, or even pointless.

**Comment by michael-sevcik** [comment]
> So you suggest making the whole (almost) dictionary by our own? I am not against that since finding right terms online is painful, or even pointless.

I would suggest trying to find some terms that fit, e.g. house could be one of them, but most entities will have to be described by our dictionary.

**Comment by michael-sevcik** [comment]
> Good job @michael-sevcik, looks great, thank you for the efford. Why not put the whole thing in a file already?

@patinoboh thx. I am not against putting it into a file, I thought this would be simpler in terms of merge conflicts and also I have the one term with unfished definition, that I need to consult with Klímek.

**Comment by patinoboh** [comment]
I believe guys are onto something, but are too selfish to tell anything. However they seem to have found almost everything, let's just wait for them. ETA 15min imo

**Comment by rastoboh** [comment]
we found dictionary[dbpedia-owl](http://dbpedia.org/ontology) that has almost everything

**Comment by patinoboh** [comment]
I suggest, firstly we create a table with all the URI (something like here) for all our entities, properties and even "vazby". That we can easily figure out what's missing and what we need to define ourselfs. Do you all agree? Should I make the file with template? In my opition with this figured out writing the whole project rdf will be much easier.
@everyone

**Comment by patinoboh** [comment]
Please check out file I created [here](https://github.com/michael-sevcik/NPRG036-Data-Formats/compare/main...rdf_rit_dopice_fstym_patrik). If you thing it is helpful, merge it and start filling it out.
@michael-sevcik @rastoboh @rastoboh

**Comment by patinoboh** [comment]
I believe this issue has served it's purpose (or tried to) and it's time to close it.
