### ISSUE TITLE
Tranform the conceptual model to RDF description 

### ISSUE THREAD

**Issue by michael-sevcik** [michael-sevcik/NPRG036-Data-Formats#18]
Tranform the [textual description](https://github.com/michael-sevcik/NPRG036-Data-Formats/blob/main/domain.txt) to the form shown in #17 .

**Comment by patinoboh** [comment]
How should the output even look like? Should we have one file for dictionary and one for the whole project? What are the extensions for the files?

**Comment by michael-sevcik** [comment]
@patinoboh the description is [here](https://jakub.klímek.com/nprg036-hw2#how).  I guess that our custom dictionary terms will be in `data.ttl` together with the example data inserts.

**Comment by patinoboh** [comment]
@ori-no has used [dbo:Street](http://dbpedia.org/resource/classes#Street) as a domain for _located_in_ link, however there is no such rdf class/entity online. Where did you find it? It is my part to create rdf description for Street so now I do not know what to use. Thank you for this and informing us as well </3. Please react to this asap @ori-no.
Also I do not see a point of making branches when you do not submit merge request AND when everyones uses different folders and names.

**Comment by ori-no** [comment]
https://dbpedia.org/ontology/Street.
I already also have your Street and House in development, ready in  minutes.
Then I am about to combine all of our separately made rdfs and put it (by hand) into one data.ttl file in 02 folder.

**Comment by ori-no** [comment]
Then I think it would be time to start doing the instances, as said in homework assignment.
Can you do that @patinoboh ?

**Comment by patinoboh** [comment]
Sorry, my bad, tho it's weird I didn't see it [in the list of all classes](https://dbpedia.org/ontology/).
Are these entities all that's left? It seem like it. I checked @rastoboh, but I do not know whether it's finished due to no comment and no merge request.
If it is all to the rdf concept we should close this issue and I'll start making the rdf instances.
Also please attach all files right into _rdf_ folder as said in the assignment.

**Comment by rastoboh** [comment]
Sorryy, i thought i submitted merge request. It is finished, but i just need someone to check it.

**Comment by ori-no** [comment]
I think best would be if we all check the final version and approve it.

**Comment by rastoboh** [comment]
I agree. And if i didnt submit merge request then i guess i dont know how to do it. :((

**Comment by patinoboh** [comment]
What's holding us from creating THE final file? We definitely need to check that afterwards. Now it seems best to close all branches dedicated for this part of the task, put it all in one file and than check that.

**Comment by ori-no** [comment]
Sorry guys I got stuck on finding rdf for RGB hexadecimal code.
Can you @patinoboh help me find such thing suitable for property of building?

**Comment by patinoboh** [comment]
Seem like we need different aproach for this atribute. Perhaps the use of hexadecimal code for color attribute was not the best.
I suggest few possible fixes :
1. Remove enitre color attribute and replace it with something easier e.g. number of floors in the house
2. Change it to RGB and create our own class,... to difficult
3. Using [this](https://dbpedia.org/ontology/colourHexCode)

Update : I felt hopeless however the third point is exactly what we need. @ori-no

**Comment by ori-no** [comment]
@patinoboh popici the third point is exactly what we need

**Comment by ori-no** [comment]
Now it is compatible to create the instances and the image so this issue is imo closed
