### ISSUE TITLE
Change UML diagram for street entity

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#2]
I had to change aributes of steet entity. Me and my team decided that streed must have a *name*. Also we do not need a *drain* atribute. Domain file is already adapted for these changes.

**Comment by patinoboh** [comment]
New .png has to be generated where Street has atributes -name and -sidewalk. Leader get to it asap @rastoboh

**Comment by ori-no** [comment]
Confirming issue still exists, plus the names that are not single word should be connected via _underline_ and **not** space. Please resolve @rastoboh.
