### ISSUE TITLE
Create rdf example instances for rdf conceptual model

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#22]
The rdf conpetual model is almost finished so the next step is to create exmple instances for Kelimek to jerk off to. I'll try do this myself but need someone to check it afterwards so I am assigning all of you for now haha

**Comment by ori-no** [comment]
I do think the easiest way for you would be to use AI tools because it is just boring writing.
The main aim would be to meet the quotes and to be kind of realistic. Meaning that we should not have 3 villages with 1 house and 1 occupant in each of them.

**Comment by patinoboh** [comment]
I understand the assignment and will do my best to represent the world best I can. 
Not sure about the use of AI tools for this task. I'll see how they behave and adapt accordingly. @ori-no

**Comment by ori-no** [comment]
So I created the data.ttl file in such form in which it can be clear how to initialize the instances. Minor changes in the end if we see that we did something wrong should be easy to fix. So I suggest you create new branch starting on this template and create the instances there.

**Comment by patinoboh** [comment]
I started working on it, however I am really not sure whether I am doing it right.
I created few classes, could you please check it really quick?

```
<ex:Rovinka> a dbo:Town;
    ex:townName "Rovinka"@sk;
    ex:hasFlag "true"^^xsd:boolean;
    ex:hasBroadcast "true"^^xsd:boolean.

<ex:Michal> a ex:Occupant;
    ex:dateFrom "2018-09-01"^^xsd:date;
    ex:unpaidFees "false"^^xsd:boolean.


<ex:BlueHouse> a dbo:Building;
    ex:houseNumber "466"^^xsd:int;
    ex:hasSidewalk "true"^^xsd:boolean.
    # TODO colour
```

**Comment by patinoboh** [comment]
Thank you,
It does not add much work, will probably do it high anyway so I'll play with them a bit haha

**Comment by ori-no** [comment]
What about November!!!??? @patinoboh

**Comment by patinoboh** [comment]
No alcohole, no nicotine @ori-no 
![check](https://static.vecteezy.com/system/resources/previews/002/743/514/non_2x/green-check-mark-icon-in-a-circle-free-vector.jpg)

**Comment by ori-no** [comment]
I thought you prohibited yourself from passing on to other substances knowing it will do even more harm
