### ISSUE TITLE
Create updated scheme image with rdf properties

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#23]
Simple task, just needs someone to change the current drawio image to [rdf such as this one](https://jakub.xn--klmek-0sa.com/assets/images/nprg036-hw2-model-vocabs.svg).
Might be wise to do this asap for the better understadning of our rdf concept.

**Comment by rastoboh** [comment]
I think it would be easier if we had the final turtle file first.

**Comment by patinoboh** [comment]
Of course, there is no other way for that, I was kinda counting on the turtle being almost finished by now. @rastoboh

**Comment by rastoboh** [comment]
like i said i have my part finished, anyway i can do this task after we have final .ttl file

**Comment by ori-no** [comment]
@rastoboh there should be everything you need to convert the old image in the data.ttl. It is not the final form but is able to sevre the cause.

**Comment by rastoboh** [comment]
1.Can there be two properties with the same name for two different classes? They have different label, domain and range. (ex:dateFrom in Mayor and Occupant)
2. I found conflict between ex:mayor created by me and ori. I guess we have to delete one andOr modify some things because I created ex:Mayor not dbo:Mayor.

**Comment by michael-sevcik** [comment]
> 1.Can there be two properties with the same name for two different classes? They have different label, domain and range. (ex:dateFrom in Mayor and Occupant)

For the 1st problem I see two solutions:

1. Merge the two properties into one with domain foaf:Person
2. Keep both and rename them... I would suggest termStart and moveInDate

**Comment by michael-sevcik** [comment]
> 2. I found conflict between ex:mayor created by me and ori. I guess we have to delete one andOr modify some things because I created ex:Mayor not dbo:Mayor.

@rastoboh if the dbo:Mayor is well defined, I would keep the dbo:Mayor and only define the custom properties

**Comment by rastoboh** [comment]
ok, but we still have two definitions for ex:mayor

**Comment by ori-no** [comment]
@rastoboh you can just delete one, it is my mistake. When I did my part I did all the things I had done in the previous homework and did not look at yours.

**Comment by rastoboh** [comment]
ok ill delete yours

**Comment by rastoboh** [comment]
done
