### ISSUE TITLE
What does 6th point of the assignment mean?

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#24]
> Load the RDF data into a triplestore such as [Apache Jena Fuseki](https://jena.apache.org/documentation/fuseki2/) or [Openlink Virtuoso Open-Source](http://vos.openlinksw.com/owiki/wiki/VOS/VOSDownload) (or both). There is a [triplestore quick-start](https://docs.google.com/presentation/d/1Me_9PDk9HlSFSry2bC_XamVQpheNpJRsqI5PhhrQXhw) slide deck prepared. Openlink Virtuoso also allows you to browse the data in their Faceted search plugin.

[Assignment link](https://jakub.xn--klmek-0sa.com/nprg036-hw2#how)
I don't get it. Do we need to download dedicated software for this? Did he even fucking talk about this?

**Comment by michael-sevcik** [comment]
Yes, we do and no, he did not talk about it, or he only briefly mentioned it.

**Comment by michael-sevcik** [comment]
I believe it is only used for verifying the queries.
