### ISSUE TITLE
Creating SPARQL queries

### ISSUE THREAD

**Issue by ori-no** [michael-sevcik/NPRG036-Data-Formats#28]
I am creating new branch for creating queries. I think that data.ttl are in good form to start creatin queries about them.

**Comment by patinoboh** [comment]
Might be cool using the feature **Development** in the right panel for creating a branch. @ori-no

**Comment by patinoboh** [comment]
@ori-no I updated the [folder structure](https://github.com/michael-sevcik/NPRG036-Data-Formats/pull/30). Also added [my querry](https://github.com/michael-sevcik/NPRG036-Data-Formats/pull/30/commits/af5bc1ddbb21a618ce9461198cf132543222fab8), maybe some could check that one.

**Comment by patinoboh** [comment]
@ori-no you did not use the correct [file destination](https://jakub.xn--klmek-0sa.com/nprg036-hw2#how)

**Comment by ori-no** [comment]
@patinoboh yes I did not I apologize. I saw my mistake, however could not work in your branch for whatever reason. So if you can change it yourself please. And also the names of the folders are not as they were said to be in the homework assignment so they will need change too.

**Comment by rastoboh** [comment]
i am not sure about some querries being non trivial as requested by kelimek (including mine)

**Comment by michael-sevcik** [comment]
> i am not sure about some querries being non trivial as requested by kelimek (including mine)

@rastoboh considering we are not getting any points for this and we only have to deliver something a little reasonable, I would wait for the feedback.
