### ISSUE TITLE
Word "property" overloading

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#29]
Word property is appearing a lot recently especially in this project? I have a bit o a language barrier with this word. This word can be interpreted differently for example as : 

1. Property as in _nehnuteľnosť_ which corresponds to our data
2. Property as in _property of class_ in some rdf classes/subclasses/atributes
3. Property as an attribute - could be interpreted like this as well

Mainly I am interested in the meaning of this word in the this use : 
`
ex:townName a rdfs:Property;
`

**Comment by ori-no** [comment]
It is the way in which new vzťahu and vlastnosti are defined. No other way around it.

**Comment by patinoboh** [comment]
So it has nothing to do with property as _something you can own_? @ori-no

**Comment by ori-no** [comment]
No. In our RDF the Nehnuteľnosť or as we have in our .PNG image House, I decided to use dbo:Building.

**Comment by patinoboh** [comment]
Thanx
