### ISSUE TITLE
Start LPG

### ISSUE THREAD

**Issue by ori-no** [michael-sevcik/NPRG036-Data-Formats#35]
@michael-sevcik @patinoboh @rastoboh Is anyone planning on starting doing the LPG today? I can start in the evening. I would like if we tomorrow had every piece of homework in the verifying stage. Do you think it is doable?

**Comment by rastoboh** [comment]
sure it is doable

**Comment by michael-sevcik** [comment]
I can have a look at it as well.

**Comment by michael-sevcik** [comment]
The development associated with LPG has been split into two separate issues: #42 and #43.

**Comment by michael-sevcik** [comment]
The development associated with LPG has been split into two separate issues: #42 and #43.
