### ISSUE TITLE
Convert the queries to CYPHER

### ISSUE THREAD

**Issue by michael-sevcik** [michael-sevcik/NPRG036-Data-Formats#43]
After resolving issue #42 , we must convert the queries to CYPHER as a final step of our [HW2 journey](https://github.com/michael-sevcik/NPRG036-Data-Formats/milestone/2).

**Comment by patinoboh** [comment]
So [this](https://github.com/michael-sevcik/NPRG036-Data-Formats/pull/45) should be all for now?

**Comment by michael-sevcik** [comment]
Has anyone tested the LPG queries?

Big thanks to @ori-no for correcting my query!
