### ISSUE TITLE
Feedback implementation

### ISSUE THREAD

**Issue by michael-sevcik** [michael-sevcik/NPRG036-Data-Formats#48]
- [ ] Máte ex:Occupant rdfs:subClassOf foaf:Person ;, ale chybí ex:Occupant a rdfs:Class - říkali jsme na cvičení, že na inferenci/reasoning se spoléhat nechceme

- [ ] xsd:int není vhodný datový typ pro celé číslo. Tím je xsd:integer, pro který jsou i syntaktické zkratky

- [x] #51

- [x] #49

**Comment by patinoboh** [comment]
Resolved in [merge request](https://github.com/michael-sevcik/NPRG036-Data-Formats/pull/53)
