### ISSUE TITLE
data.ttl problem

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#54]
Might not be an issue, we just found it weird, while fixing Kelimeks requests in _data.ttl_
- [ ] Why do we use sometimes **ex:Town** and sometimes **dbo:Town**? Shouldn't we be **consistent**?
- [x]  We do not **specify** that **Town** is a **class**? There is no such code in _data.tll_

**Comment by michael-sevcik** [comment]
@patinoboh 

> Might not be an issue, we just found it weird, while fixing Kelimeks requests in _data.ttl_
> 
> 1. Why do we use sometimes **ex:Town** and sometimes **dbo:Town**? Shouldn't we be **consistent**?

The ex:Town is a relict from previous versions, the entity that is meant to be used is `dbo:Town`.

> 2. We do not **specify** that **Town** is a **class**? There is no such code in _data.tll_

This should not be needed since the `dbo:Town` is defined in an external dictionary.

**Comment by patinoboh** [comment]
Alright then,
should we change all `ex:Town` to `dbo:Town`? @michael-sevcik

**Comment by patinoboh** [comment]
[resolved](https://github.com/michael-sevcik/NPRG036-Data-Formats/pull/58)
