### ISSUE TITLE
Create corresponding csv files with headers

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#94]
- [ ] Create all tables
- [ ] Rename them to data-[12345678].csv

**Comment by patinoboh** [comment]
Do we need `Id` in middleNames? Also I do not understand what means `middleNames` attribute in `People` table? How to instanciate it? @michael-sevcik @ori-no @rastoboh ?

**Comment by michael-sevcik** [comment]
> Do we need `Id` in `middleNames`? Also I do not understand what means `middleNames` attribute in `People` table? How to instanciate it? @michael-sevcik @ori-no @rastoboh ? I think we do not need 'Id' in 'middleNames' class. Also we might omit `middleNames` attribute in `People`. (You can still join these tables using foreign key in `middleNames` table)

@patinoboh 
As we discussed during the practicals, one person can have multiple identical middle names, so we have to use the artificial Id to distinguish between the records.
