### ISSUE TITLE
Celebrate the completion of the Data Formats practicals

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#97]
- KEDY? 
- KDE?
- Pozveme aj Kelímka?

**Comment by michael-sevcik** [comment]
> * KEDY?

Úplně to nevidím do Vánoc. V tom prvním týdnu?

> * KDE?

Dal bych dýmku někde, ok?

**Comment by rastoboh** [comment]
oh yess
