### ISSUE TITLE
Make the jenna riot transformation

### ISSUE THREAD

**Issue by patinoboh** [michael-sevcik/NPRG036-Data-Formats#99]
There is a way to generate full rdf only with tabular command : `rdf serialize --input-format tabular --output-format turtle --minimal --decode-uri data.csv-metadata.json`
However mr. Kelimek wants us to use it to generate **Ntriples** like this : `rdf serialize --input-format tabular --output-format ntriples --minimal --decode-uri data.csv-metadata.json`
And then use jenna riot magic to transform [Ntriples](e8b84134945d4862f177d9c0b45d990edeaa6c89) into turtle.

**Comment by michael-sevcik** [comment]
@patinoboh, the output really looks almost great, we just have to deal with the common error: 
![image](https://github.com/michael-sevcik/NPRG036-Data-Formats/assets/106611909/2495d73a-c5d5-4602-a954-57aece179df2)

That's probably the reason why we should use the Apache Jena.

I would sugest removing removing the forbidden prefixes (see the note from the common errors above) from the metadate file and manually fixing the URIs

**Comment by patinoboh** [comment]
Do we use any "forbidden" prefixes?
I thought about this and decided to use absolute IRI representation, which should use the <>. Is there a problem with this solution?
Otherwise I think there is not idea to tell rdf-tabular not to export <>. That's probably why Vlado uses absolute IRIs and <> everywhere as well.
Can, perhaps, jenna change absolute IRIs into prefixed?
@michael-sevcik

**Comment by michael-sevcik** [comment]
> Do we use any "forbidden" prefixes? I thought about this and decided to use absolute IRI representation, which should use the <>. Is there a problem with this solution? Otherwise I think there is not idea to tell rdf-tabular not to export <>. That's probably why Vlado uses absolute IRIs and <> everywhere as well. Can, perhaps, jenna change absolute IRIs into prefixed? @michael-sevcik

@patinoboh, It turns out that jena can do that -> #100
